comment: false

language: R

sudo: false

cahce: packages

after_success:

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true

- Rscript -e 'covr::codecov()'
